#22-As a host, I want to be able to search among energisers by name / description-JustinasBrazauskas
AzinYad/Code-Crafters-Team-6 pull request #27
Opened 2023-02-27 22:01 UTC by JustinasBrazauskas

## Naming Rules

Name your PR like this: ISSUENUMBER-TITLE-YOURNAME

## Description

I created a component , SearchEnergizers. But I got stil some bugs kind like this:"the variable setSearchEnergizers is declared but not used". I'm not sure how to fix it? 
## Related to

Make sure you include the issue number with a hash sign # so Github can link this PR to the right issue, like this:

Fixes #1

## Checklist:

- [] My code follows the style guidelines of this project
- [ ] I have carefully reviewed my own code
- [ ] I have commented my code
- [ ] I have updated any documentation

2023-02-27 23:38 UTC, bertilnilsson requested changes

2023-02-27 23:38 UTC, bertilnilsson commented on client/src/pages/components/SearchEnergizers.js
> +        <div key={energizer.name}>
Shouldn't these be rendered with a shared component?

2023-02-27 23:38 UTC, bertilnilsson commented on package.json
> +		"node": "^19.6.1",
`node` should not be installed as a dependency, it's the engine

2023-02-27 23:38 UTC, bertilnilsson commented on server/api.js
> +router.post("api/energizers", (req, res) => {
Does this not change the API url to `api/api/energizers`?

2023-02-27 23:38 UTC, bertilnilsson commented on server/db.js
> -	let client;
This disables the database connection - included by mistake?

2023-02-27 23:39 UTC, bertilnilsson commented
Make sure you put the right issue number on the `Fixes #...` line in your description

2023-02-27 23:44 UTC, bertilnilsson commented on client/src/pages/components/SearchEnergizers.js
> +  const filteredEnergizers = energizers.filter((energizer) => {
Would this not only run once when the component is first instantiated, i.e. it should it not run when you do the handleSearch (on change) above and update the state? 

Also don't you need to maintain both a state of all energizers and the filtered ones?

2023-03-11 18:03 UTC, JustinasBrazauskas commented
closing  this because  of #46

2023-03-11 18:03 UTC, closed without merging